### ISSUE TITLE
Add "Edit this page" link as seen in Symfony Docs

### ISSUE THREAD

**Issue by rogamoore** [api-platform/docs#546] opened 2018-07-22 19:29 UTC
To help improve the docs I would like to suggest the addition of an "Edit this page" link or button similar as we have on the Symfony Docs: http://symfony.com/doc/current/setup.html

That would save contributors some time to find the right file in the Github repo to create a PR.

I'm happy to create a PR to add these links, but first I would like to know your opinions. What do you think?

**Comment by antograssiot** [comment] 2018-07-23 05:37
this seems a duplicate of https://github.com/api-platform/website/issues/57

**Comment by alanpoulain** [comment] 2019-02-02 17:00
Has been done.

**Closed by alanpoulain** 2019-02-02 17:00 UTC
